### ISSUE TITLE
fedbadges fails when trying to connect to mbs/mbs.fedoraproject.org

### ISSUE THREAD

**Issue by sayanchowdhury** [fedora-infra/fedbadges#53]
<detail>

Message
-------
[2017-04-10 23:32:00][moksha.hub   ERROR]
```python
Couldn't talk to pkgdb2 for u'mbs/mbs.fedoraproject.org', 404, u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n'
```

Process Details
---------------
- host:     badges-backend01.phx2.fedoraproject.org
- PID:      31829
- name:     fedmsg-hub
- command:  /usr/bin/python /usr/bin/fedmsg-hub
- msg_id:   2017-05fb9f63-1e1d-489a-82bd-de45e3fd92b5
  File "/usr/lib/python2.7/site-packages/fedbadges/utils.py", line 96 in inner
    log.exception(e)
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fedbadges/utils.py", line 94, in inner
    return method(self, *args, **kwargs)
  File "/usr/lib/python2.7/site-packages/fedbadges/rules.py", line 371, in matches
    return self.specialization.matches(msg)
  File "/usr/lib/python2.7/site-packages/fedbadges/rules.py", line 418, in matches
    user=expectation['user'],
  File "/usr/lib/python2.7/site-packages/fedbadges/utils.py", line 145, in get_pkgdb_packages_for
    return _getter(user)
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 1053, in decorate
    should_cache_fn)
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 657, in get_or_create
    async_creator) as value:
  File "/usr/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 158, in __enter__
    return self._enter()
  File "/usr/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 98, in _enter
    generated = self._enter_create(createdtime)
  File "/usr/lib/python2.7/site-packages/dogpile/core/dogpile.py", line 149, in _enter_create
    created = self.creator()
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 625, in gen_value
    created_value = creator()
  File "/usr/lib/python2.7/site-packages/dogpile/cache/region.py", line 1049, in creator
    return fn(*arg, **kw)
  File "/usr/lib/python2.7/site-packages/fedbadges/utils.py", line 143, in _getter
    return _get_pkgdb2_packages_for(config, user)
  File "/usr/lib/python2.7/site-packages/fedbadges/utils.py", line 166, in _get_pkgdb2_packages_for
    data = _get_page(1)
  File "/usr/lib/python2.7/site-packages/fedbadges/utils.py", line 159, in _get_page
    username, req.status_code, req.text))
IOError: Couldn't talk to pkgdb2 for u'mbs/mbs.fedoraproject.org', 404, u'<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">\n<title>404 Not Found</title>\n<h1>Not Found</h1>\n<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>\n'

</detail>

**Comment by sayanchowdhury** [comment]
Fixed in #55
