### ISSUE TITLE
Make fedbadges more resilient if a message has no user

### ISSUE THREAD

**Issue by mscherer** [fedora-infra/fedbadges#79]
My mailbox was full of mail from fedbadge because https://github.com/fedora-infra/fedbadges/blob/develop/fedbadges/rules.py#L218-L224 fail when user is null:

```
user for user in awardees if not (
                user.startswith('192.168.') or
                user.startswith('10.')
            )
```

It seems to come from pagure git replication. I already removed the mail, but the problem was that user was "none".

**Comment by mscherer** [comment]
```
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/fedbadges/consumers.py", line 231, in consume
    for recipient in badge_rule.matches(msg):
  File "/usr/lib/python2.7/site-packages/fedbadges/rules.py", line 221, in matches
    user.startswith('192.168.') or
AttributeError: 'NoneType' object has no attribute 'startswith'
```

Triggered by https://pagure.io/pgnd/lemonldap-ng-UPSTREAM-MIRROR so likely a message like this one: 
https://apps.fedoraproject.org/datagrepper/id?id=2021-9ee3e4d9-fc17-4929-86f7-cc779a37646d&is_raw=true&size=extra-large

**Comment by mscherer** [comment]
From a quick reading of the code, I guess this come from https://github.com/fedora-infra/fedbadges/blob/3ecdbfaccef7eb53a7c93cf871aa2ad3e941b943/fedbadges/utils.py#L121 

The commit has a author with "full name: Null", but since there is 2 authors, this pass the verification of the result of get_pagure_author: https://github.com/fedora-infra/fedbadges/blob/develop/fedbadges/rules.py#L194-L196 

And later fail.
